### ISSUE TITLE
Slight bug in README.md documentation

### ISSUE THREAD

**Issue by justinmchase** [smikes/CppUnitLite#2]
The part where you're showing how to add `cppunitlite` in the `include_dirs` is slightly wrong, I think. It seems like the end should actually be `")'`
So this:
```
'<!(node -e "require(\'cpppunitlite\')'
```

Should actually be: 
```
'<!(node -e "require(\'cppunitlite\')")'
```

**Comment by smikes** [comment]
Thanks! I will fix it.
