### ISSUE TITLE
Wrong delete operator being used

### ISSUE THREAD

**Issue by Brandon-T** [smikes/CppUnitLite#7]
in Failure.cpp, it has:

```C++
char *stage = new char [strlen (part1)
					+ expected.size ()
					+ strlen (part3)
					+ actual.size ()
					+ 1];
///other code here..

	delete stage;  //This is incorrect.. it should be `delete[]` and not `delete`.
```

It uses `delete` instead of `delete[]` on `stage` which is an array. This is undefined behaviour and can lead to unexpected crashes.

In SimpleString.cpp, it has:

```C++
SimpleString SimpleString::operator= (const SimpleString& other)
{
	delete buffer;  //This is incorrect.. it should be `delete[]` and not `delete`.
	buffer = new char [other.size() + 1];
	strcpy(buffer, other.buffer);
	return *this;
}
```
It uses `delete` instead of `delete[]` for `buffer` which is an array. This is undefined behaviour and can lead to unexpected crashes.

**Comment by smikes** [comment]
Oh, nice catch.  Have you reported this upstream?

**Comment by Brandon-T** [comment]
Hey, I’ve only reported it here. No where else :(

Where do I need to report it?

**Comment by smikes** [comment]
So it turns out I cannot find the proper upstream.  I'll see if I can reach Michael.  In the meantime, I have merged your fix - thanks!
